# Use the README file as a reference to customize settings.

EntrMissionUser:
  fields:
    default: user, mission, state
    form: 
    options:
      selectors: state
  relationships: user, mission
  application: User Management
