# Use the README file as a reference to customize settings.

EntrMissionUser:
  order_by: -created_at
  fields:
    default: user, mission, state, user.missions_applied, user.missions_todo, user.missions_done, user.missions_refused
    list: user, mission, state
    edit :  user, mission, state
    show: user, mission, state
    form: user, mission, state
    options:
      selectors: state
      templates:
        state: status
  relationships: user, mission
  application: Missions Management
  