# Use the README file as a reference to customize settings.

Mission:
  order_by: -missions.created_at
  fields:
    default: category, state, euros, epices, points, title, resume, description, image, begin_date, end_date, euros, epices, points
    list: title, category, state, user_interested, begin_date, end_date, euros, epices, points
    show: title, category, state, user_interested, euros, epices, points
    form:
    options:
      selectors: category, state
      templates:
        begin_date: date
  relationships: entr_mission_users
  description : Manage Missions
  application: Missions Management
  actions:
    show : send_mail_to_users, choose_user
  filters: begin_date, category, state
  search: title, description, resume
  scopes: pending_missions, processing_missions, finished_missions
