# Use the README file as a reference to customize settings.

User:
  fields:
    default: to_label, points, epices, cash
    list : to_label, username, grade, email, points, epices, cash, technologies_known, technologies_want
  relationships: comments, entr_mission_users, missions
  application: User Management

