# Use the README file as a reference to customize settings.

User:
  fields:
    default: username, f_name, l_name, grade, email, points, epices, cash, technologies_known, technologies_want
    list : username, f_name, l_name, grade
    form: 
  relationships: comments, entr_mission_users, missions
  application: User Management

